name: notes_firebase_ddd
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.25
  auto_route: ^3.0.4
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.4
  dartz: ^0.10.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_hooks: ^0.18.0
  flutter_slidable: ^0.6.0
  freezed_annotation: ^0.15.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  implicitly_animated_reorderable_list: ^0.4.2
  injectable: ^1.5.0
  json_annotation: ^4.3.0
  kt_dart: ^0.10.0
  provider: ^6.0.1
  rxdart: ^0.27.2
  uuid: ^3.0.5

dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1
  injectable_generator: ^1.5.2
  json_serializable: ^6.0.1
  lint: ^1.7.2

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
